# AEM configuration for local development environment

nodes:

- node: aem-author
  roles:
  - role: wcm-io-samples-aem-cms
    variant: aem-author

- node: aem-publish
  roles:
  - role: wcm-io-samples-aem-cms
    variant: aem-publish

config:
  contentPackage.group: wcm-io-samples
  app.sampleContent: true

  # Log levels
  log:
    projectSpecificLogLevel: info

  # Replication configuration not required for AEM cloud service
  replication:
    author.generatePackage: false
    publish.generatePackage: false

  # Use this AEM configuration for DEV environments in AEM Cloud service
  # For the DEV dispatcher the PROD configuration is reused
  cloudManager.target:
  - dev
